expose:
  type: ingress
  tls:
    enabled: false
    certSource: secret
    secret:
      secretName: tls-cert

  ingress:
    controller: default
    className: nginx
    hosts:
      core: harbor.cloud.worker
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"


externalURL: https://harbor.cloud.worker

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      size: 250Gi
      storageClass: "local-path-retain"
    chartmuseum:
      size: 30Gi
      storageClass: "local-path-retain"
    database:
      size: 10Gi
      storageClass: "local-path-retain"
    redis:
      size: 5Gi
      storageClass: "local-path-retain"
    jobservice:
      size: 10Gi
      storageClass: "local-path-retain"

metrics:
  enabled: true
