grafana:
    adminUser: ENC[AES256_GCM,data:IEqY0bA=,iv:Q0Q40DrzujYchm/TNtse2YCYjxruBf3swmuizl8LTzQ=,tag:gg83C179lY/OwLwgnCTc1g==,type:str]
    adminPassword: ENC[AES256_GCM,data:FNSMLacp,iv:8ww7S0RV4kmzcbwWsQ8fnXgUz4qjEjQQxK84CCuP1sg=,tag:FhbPHymmZnDL80F6ZqVTeg==,type:str]
sops:
    age:
        - recipient: age1nhn8dadwmzsjw4jztasxy88pk66y3fw087u8uquvg79vfrnckpkqdq5rrh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bnFrRUx1RmsrbENyK2Y2
            aXc1T092MG9LTDNkM0tmTHgrT3IyVXdvc1YwClpDT2oyN2YyczJFN29McDhGWHNM
            QUpFZ1J1YXZ1S3RONHduYjR2blBjQ1UKLS0tIEUrWUdaeVFqc21UTHRleVN6UWs2
            K1lBcXhrSWY4VjdCL2JQK3F3TzBRR2cKH9Mix/KJrxqVz838Uj0FOS7IYLWXwKT2
            /WAU9CBUl9FQmdofyT4H0/GuUgMkSXvz4Ozx154o/zIEqxKUmwO5/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T20:46:09Z"
    mac: ENC[AES256_GCM,data:O5ywoKUE8ff8vwFm+QkC6WwSLz6gkHJ7ao8RZY1RA9Kwhy5qocKDeRtRSXKOiS5EHpEjBs/jsCXVtDjF3k7Li9pug594TeOSa/jdrUvlsO2gmYC4Ah0g+JLe3FSkBztdvH2Jv3TUh558NUeDU+bz1RJl90GOidOficwYlECjrWI=,iv:wxf4686KFBJn+iZqxkQ8oqsbYGn3lAQiBe9OaarIJok=,tag:Ay+/jxFaxe7bk36ANogPgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
